let stations = [
    "Boulogne-Jean-Jaurès ligne-10",
    "Duroc ligne-13",
    "Duroc ligne-10",
    "Cluny-La Sorbonne ligne-10",
    "Mirabeau ligne-10",
    "Porte d'Auteuil ligne-10",
    "Cardinal-Lemoine ligne-10",
    "Avenue Emile-Zola ligne-10",
    "Charles Michels ligne-10",
    "Boulogne Pont de Saint-Cloud ligne-10",
    "Chardon-Lagache ligne-10",
    "Jourdain ligne-11",
    "Goncourt (Hôpital Saint-Louis) ligne-11",
    "Telegraphe ligne-11",
    "Rambuteau ligne-11",
    "Pyrenees ligne-11",
    "Mairie des Lilas ligne-11",
    "Solférino ligne-12",
    "Mairie d'Issy ligne-12",
    "Vaugirard (Adolphe Chérioux) ligne-12",
    "Lamarck-Caulaincourt ligne-12",
    "Notre-Dame des Champs ligne-12",
    "Assemblée Nationale ligne-12",
    "Falguière ligne-12",
    "Volontaires ligne-12",
    "Saint-Georges ligne-12",
    "Abbesses ligne-12",
    "Notre-Dame de Lorette ligne-12",
    "Front Populaire ligne-12",
    "Porte de Versailles tramway-3a",
    "Porte de Versailles tramway-2",
    "Porte de Versailles ligne-12",
    "Trinité-d'Estienne d'Orves ligne-12",
    "Rue du Bac ligne-12",
    "Porte de la Chapelle tramway-3b",
    "Porte de la Chapelle ligne-12",
    "Jules Joffrin ligne-12",
    "Rennes ligne-12",
    "Marx-Dormoy ligne-12",
    "Corentin-Celton ligne-12",
    "Convention ligne-12",
    "Pernety ligne-13",
    "Châtillon Montrouge ligne-13",
    "Plaisance ligne-13",
    "Carrefour-Pleyel ligne-13",
    "Brochant ligne-13",
    "Gabriel-Péri ligne-13",
    "La Fourche ligne-13",
    "Gaité ligne-13",
    "Saint-Denis-Universite ligne-13",
    "Varenne ligne-13",
    "Malakoff-Plateau de Vanves ligne-13",
    "Mairie de Clichy ligne-13",
    "Mairie de Saint-Ouen ligne-13",
    "Porte de Saint-Ouen ligne-13",
    "Porte de Vanves ligne-13",
    "Porte de Vanves tramway-3a",
    "Garibaldi ligne-13",
    "Saint-Denis-Porte de Paris ligne-13",
    "Basilique de Saint-Denis ligne-13",
    "Saint-Francois-Xavier ligne-13",
    "Porte de Clichy ligne-13",
    "Malakoff-Rue Etienne Dolet ligne-13",
    "Les Agnettes ligne-13",
    "Asnieres-Gennevilliers Les Courtilles ligne-13",
    "Guy-Môquet ligne-13",
    "Liège ligne-13",
    "Cour Saint-Emilion ligne-14",
    "Bibliotheque-Francois Mitterrand ligne-14",
    "Olympiades ligne-14",
    "Bry-sur-Marne rer-a",
    "Lognes rer-a",
    "Boissy-Saint-Léger rer-a",
    "Conflans-Fin d'Oise rer-a",
    "Neuville-Université rer-a",
    "La Croix-de-Berny rer-b",
    "Sceaux rer-b",
    "Vert-Galant rer-b",
    "Sevran Livry rer-b",
    "La Hacquinière rer-b",
    "Sevran-Beaudottes rer-b",
    "Lozère rer-b",
    "Luxembourg rer-b",
    "Le Guichet rer-b",
    "Fontaine-Michalon rer-b",
    "Laplace rer-b",
    "Le Bourget rer-b",
    "Bures-sur-Yvette rer-b",
    "Villepinte rer-b",
    "Blanc-Mesnil rer-b",
    "Saint-Michel Notre-Dame rer-b",
    "Saint-Rémy-lès-Chevreuse rer-b",
    "Gentilly rer-b",
    "Massy-Verrières rer-b",
    "Palaiseau Villebon rer-b",
    "Bagneux rer-b",
    "Antony rer-b",
    "Palaiseau rer-b",
    "Port Royal rer-b",
    "Parc de Sceaux rer-b",
    "Parc des Expositions rer-b",
    "Arcueil-Cachan rer-b",
    "Orsay-Ville rer-b",
    "Mitry-Claye rer-b",
    "Massy-Palaiseau rer-b",
    "La Courneuve-Aubervilliers rer-b",
    "La Plaine-Stade de France rer-b",
    "Aulnay-sous-Bois rer-b",
    "Bourg-la-Reine rer-b",
    "Fontenay-aux-Roses rer-b",
    "Villeparisis rer-b",
    "Drancy rer-b",
    "Les Baconnets rer-b",
    "Gif-sur-Yvette rer-b",
    "Courcelle-sur-Yvette rer-b",
    "Robinson rer-b",
    "Aeroport Charles de Gaulle 1 rer-b",
    "Aeroport Charles de Gaulle 2 TGV rer-b",
    "Desnouettes tramway-3a",
    "Pont garigliano - hopital europeen george pompidou tramway-3a",
    "Georges brassens tramway-3a",
    "Didot tramway-3a",
    "Brancion tramway-3a",
    "Jean moulin tramway-3a",
    "Alexandra david-neel tramway-3a",
    "Montempoivre tramway-3a",
    "Porte d'orleans tramway-3a",
    "Cite universitaire tramway-3a",
    "Cite universitaire rer-b",
    "Stade charlety - porte de gentilly tramway-3a",
    "Poterne des peupliers tramway-3a",
    "Montsouris tramway-3a",
    "Maryse bastie tramway-3a",
    "Avenue de france tramway-3a",
    "Baron le roy tramway-3a",
    "Delphine seyrig tramway-3b",
    "Butte du chapeau rouge tramway-3b",
    "Hopital robert debre tramway-3b",
    "Adrienne bolland tramway-3b",
    "Severine tramway-3b",
    "Canal saint denis tramway-3b",
    "Marie de miribel tramway-3b",
    "Rosa parks tramway-3b",
    "Porte d'aubervilliers tramway-3b",
    "Colette besson tramway-3b",
    "Ella fitzgerald - grands moulins de pantin tramway-3b",
    "Suresnes longchamp tramway-2",
    "Brimborion tramway-2",
    "Belvedere tramway-2",
    "Porte d'issy tramway-2",
    "Les milons tramway-2",
    "Suzanne lenglen tramway-2",
    "Les coteaux tramway-2",
    "Henri farman tramway-2",
    "Musee de sevres tramway-2",
    "Parc de st-cloud tramway-2",
    "Puteaux tramway-2",
    "Charlebourg tramway-2",
    "Les fauvelles tramway-2",
    "Faubourg de l'arche tramway-2",
    "Meudon sur-seine tramway-2",
    "Les moulineaux tramway-2",
    "Jacques-henri lartigue tramway-2",
    "Issy - val de seine tramway-2",
    "Victor basch tramway-2",
    "Jacqueline auriol tramway-2",
    "Pont de bezons tramway-2",
    "Parc pierre lagravere tramway-2",
    "Victor Hugo ligne-2",
    "Pigalle ligne-12",
    "Pigalle ligne-2",
    "La Chapelle ligne-2",
    "Philippe Auguste ligne-2",
    "Place de Clichy ligne-2",
    "Place de Clichy ligne-13",
    "Père-Lachaise ligne-2",
    "Père-Lachaise ligne-3",
    "Porte Dauphine (Maréchal de Lattre de Tassigny) ligne-2",
    "Barbès-Rochechouart ligne-4",
    "Barbès-Rochechouart ligne-2",
    "Belleville ligne-11",
    "Belleville ligne-2",
    "Colonel Fabien ligne-2",
    "Villiers ligne-2",
    "Villiers ligne-3",
    "Blanche ligne-2",
    "Stalingrad ligne-7",
    "Stalingrad ligne-5",
    "Stalingrad ligne-2",
    "Anvers ligne-2",
    "Monceau ligne-2",
    "Alexandre-Dumas ligne-2",
    "Avron ligne-2",
    "Jaurès ligne-7-bis",
    "Jaurès ligne-5",
    "Jaurès ligne-2",
    "Ménilmontant ligne-2",
    "Ternes ligne-2",
    "Courcelles ligne-2",
    "Couronnes ligne-2",
    "Rome ligne-2",
    "Saint-Placide ligne-4",
    "Strasbourg-Saint-Denis ligne-8",
    "Strasbourg-Saint-Denis ligne-4",
    "Strasbourg-Saint-Denis ligne-9",
    "Montparnasse-Bienvenue ligne-13",
    "Montparnasse-Bienvenue ligne-6",
    "Montparnasse-Bienvenue ligne-4",
    "Montparnasse-Bienvenue ligne-12",
    "Saint-Germain des Prés ligne-4",
    "Gare de l'Est (Verdun) ligne-4",
    "Gare de l'Est (Verdun) ligne-7",
    "Gare de l'Est (Verdun) ligne-5",
    "Marcadet-Poissonniers ligne-4",
    "Marcadet-Poissonniers ligne-12",
    "Etienne Marcel ligne-4",
    "Château Rouge ligne-4",
    "Saint-Michel ligne-4",
    "Château d'Eau ligne-4",
    "Mouton-Duvernet ligne-4",
    "Alésia ligne-4",
    "Gare du Nord ligne-4",
    "Gare du Nord ligne-5",
    "Gare du Nord rer-b",
    "Les Halles ligne-4",
    "Odéon ligne-10",
    "Odéon ligne-4",
    "Denfert-Rochereau ligne-6",
    "Denfert-Rochereau ligne-4",
    "Denfert-Rochereau rer-b",
    "Porte de Clignancourt ligne-4",
    "Raspail ligne-6",
    "Raspail ligne-4",
    "Mairie de Montrouge ligne-4",
    "Place d'Italie ligne-6",
    "Place d'Italie ligne-5",
    "Place d'Italie ligne-7",
    "Bobigny-Pablo-Picasso ligne-5",
    "Porte de Pantin ligne-5",
    "Porte de Pantin tramway-3b",
    "Eglise de Pantin ligne-5",
    "Saint-Marcel ligne-5",
    "Oberkampf ligne-5",
    "Oberkampf ligne-9",
    "Laumière ligne-5",
    "Bobigny-Pantin (Raymond Queneau) ligne-5",
    "Bréguet-Sabin ligne-5",
    "Campo-Formio ligne-5",
    "Richard-Lenoir ligne-5",
    "Hoche ligne-5",
    "Péreire ligne-3",
    "Sentier ligne-3",
    "République ligne-8",
    "République ligne-11",
    "République ligne-5",
    "République ligne-3",
    "République ligne-9",
    "Réaumur-Sébastopol ligne-4",
    "Réaumur-Sébastopol ligne-3",
    "Anatole-France ligne-3",
    "Porte de Bagnolet tramway-3b",
    "Porte de Bagnolet ligne-3",
    "Porte de Champerret ligne-3",
    "Quatre Septembre ligne-3",
    "Louise Michel ligne-3",
    "Arts-et-Métiers ligne-11",
    "Arts-et-Métiers ligne-3",
    "Wagram ligne-3",
    "Pont de Levallois-Bécon ligne-3",
    "Saint-Lazare ligne-14",
    "Saint-Lazare ligne-3",
    "Saint-Lazare ligne-12",
    "Saint-Lazare ligne-13",
    "Gallieni (Parc de Bagnolet) ligne-3",
    "Gambetta ligne-3-bis",
    "Gambetta ligne-3",
    "Parmentier ligne-3",
    "Europe ligne-3",
    "Bourse ligne-3",
    "Rue Saint-Maur ligne-3",
    "Opéra ligne-8",
    "Opéra ligne-3",
    "Opéra ligne-7",
    "Temple ligne-3",
    "Malesherbes ligne-3",
    "Havre-Caumartin ligne-3",
    "Havre-Caumartin ligne-9",
    "Saint-Fargeau ligne-3-bis",
    "Pelleport ligne-3-bis",
    "Nation ligne-1",
    "Nation rer-a",
    "Nation ligne-2",
    "Nation ligne-6",
    "Nation ligne-9",
    "Concorde ligne-8",
    "Concorde ligne-12",
    "Concorde ligne-1",
    "Bastille ligne-8",
    "Bastille ligne-1",
    "Bastille ligne-5",
    "Louvre-Rivoli ligne-1",
    "Bérault ligne-1",
    "Champs-Elysées-Clémenceau ligne-13",
    "Champs-Elysées-Clémenceau ligne-1",
    "Reuilly-Diderot ligne-8",
    "Reuilly-Diderot ligne-1",
    "George V ligne-1",
    "Argentine ligne-1",
    "Franklin-Roosevelt ligne-9",
    "Franklin-Roosevelt ligne-1",
    "Palais-Royal (Musée du Louvre) ligne-1",
    "Palais-Royal (Musée du Louvre) ligne-7",
    "Pont de Neuilly ligne-1",
    "Saint-Mandé ligne-1",
    "Château de Vincennes ligne-1",
    "Esplanade de la Défense ligne-1",
    "Châtelet ligne-11",
    "Châtelet ligne-14",
    "Châtelet ligne-1",
    "Châtelet ligne-4",
    "Châtelet ligne-7",
    "Porte Maillot ligne-1",
    "Charles de Gaulle-Etoile ligne-6",
    "Charles de Gaulle-Etoile ligne-2",
    "Charles de Gaulle-Etoile rer-a",
    "Charles de Gaulle-Etoile ligne-1",
    "Tuileries ligne-1",
    "Les Sablons (Jardin d'acclimatation) ligne-1",
    "Porte de Vincennes ligne-1",
    "Porte de Vincennes tramway-3b",
    "Porte de Vincennes tramway-3a",
    "Gare de Lyon ligne-14",
    "Gare de Lyon ligne-1",
    "Gare de Lyon rer-a",
    "Saint-Paul (Le Marais) ligne-1",
    "Hôtel de Ville ligne-11",
    "Hôtel de Ville ligne-1",
    "La Défense (Grande Arche) tramway-2",
    "La Défense (Grande Arche) rer-a",
    "La Défense (Grande Arche) ligne-1",
    "Porte des Lilas ligne-3-bis",
    "Porte des Lilas tramway-3b",
    "Porte des Lilas ligne-11",
    "Simplon ligne-4",
    "Vavin ligne-4",
    "Cité ligne-4",
    "Porte d'Orléans (Général Leclerc) tramway-3a",
    "Porte d'Orléans (Général Leclerc) ligne-4",
    "Saint-Sulpice ligne-4",
    "Picpus ligne-6",
    "Ourcq ligne-5",
    "Gare d'Austerlitz ligne-5",
    "Gare d'Austerlitz ligne-10",
    "Quai de la Rapée ligne-5",
    "Jacques-Bonsergent ligne-5",
    "Sèvres-Lecourbe ligne-6",
    "Bel-Air ligne-6",
    "Bercy ligne-14",
    "Bercy ligne-6",
    "Kléber ligne-6",
    "Bir-Hakeim (Grenelle) ligne-6",
    "Dugommier ligne-6",
    "Dupleix ligne-6",
    "Cambronne ligne-6",
    "Nationale ligne-6",
    "Glacière ligne-6",
    "La Motte-Picquet-Grenelle ligne-8",
    "La Motte-Picquet-Grenelle ligne-6",
    "La Motte-Picquet-Grenelle ligne-10",
    "Edgar-Quinet ligne-6",
    "Passy ligne-6",
    "Pasteur ligne-6",
    "Pasteur ligne-12",
    "Chevaleret ligne-6",
    "Trocadéro ligne-6",
    "Trocadéro ligne-9",
    "Saint-Jacques ligne-6",
    "Quai de la Gare ligne-6",
    "Daumesnil (Félix Eboué) ligne-8",
    "Daumesnil (Félix Eboué) ligne-6",
    "Corvisart ligne-6",
    "Boissière ligne-6",
    "Villejuif-Paul Vaillant Couturier (Hôpital Paul Brousse) ligne-7",
    "Villejuif-Louis Aragon ligne-7",
    "Pierre et Marie Curie ligne-7",
    "La Courneuve-8-Mai-1945 ligne-7",
    "Poissonnière ligne-7",
    "Porte d'Ivry tramway-3a",
    "Porte d'Ivry ligne-7",
    "Château Landon ligne-7",
    "Le Kremlin-Bicêtre ligne-7",
    "Jussieu ligne-10",
    "Jussieu ligne-7",
    "Cadet ligne-7",
    "Louis Blanc ligne-7-bis",
    "Louis Blanc ligne-7",
    "Censier-Daubenton ligne-7",
    "Riquet ligne-7",
    "Pont Neuf ligne-7",
    "Porte d'Italie tramway-3a",
    "Porte d'Italie ligne-7",
    "Pont Marie (Cité des Arts) ligne-7",
    "Aubervilliers Pantin (4 Chemins) ligne-7",
    "Mairie d'Ivry ligne-7",
    "Villejuif-Léo Lagrange ligne-7",
    "Fort d'Aubervilliers ligne-7",
    "Maison Blanche ligne-7",
    "Pyramides ligne-14",
    "Pyramides ligne-7",
    "Chaussée d'Antin (La Fayette) ligne-7",
    "Chaussée d'Antin (La Fayette) ligne-9",
    "Les Gobelins ligne-7",
    "Tolbiac ligne-7",
    "Porte de la Villette ligne-7",
    "Porte de la Villette tramway-3b",
    "Le Peletier ligne-7",
    "Sully-Morland ligne-7",
    "Place Monge (Jardin des Plantes) ligne-7",
    "Porte de Choisy tramway-3a",
    "Porte de Choisy ligne-7",
    "Crimée ligne-7",
    "Corentin-Cariou ligne-7",
    "Bolivar ligne-7-bis",
    "Danube ligne-7-bis",
    "Botzaris ligne-7-bis",
    "Pré-Saint-Gervais ligne-7-bis",
    "Buttes-Chaumont ligne-7-bis",
    "Place des Fêtes ligne-7-bis",
    "Place des Fêtes ligne-11",
    "Félix Faure ligne-8",
    "Faidherbe-Chaligny ligne-8",
    "Montgallet ligne-8",
    "Porte Dorée ligne-8",
    "Porte Dorée tramway-3a",
    "Michel Bizot ligne-8",
    "Commerce ligne-8",
    "La Tour-Maubourg ligne-8",
    "Ecole Militaire ligne-8",
    "Pointe du Lac ligne-8",
    "Saint-Sébastien-Froissart ligne-8",
    "Filles du Calvaire ligne-8",
    "Chemin Vert ligne-8",
    "Ledru-Rollin ligne-8",
    "Bonne Nouvelle ligne-8",
    "Bonne Nouvelle ligne-9",
    "Grands Boulevards ligne-8",
    "Grands Boulevards ligne-9",
    "Richelieu-Drouot ligne-8",
    "Richelieu-Drouot ligne-9",
    "Porte de Charenton ligne-8",
    "Porte de Charenton tramway-3a",
    "Liberté ligne-8",
    "Maisons-Alfort-Stade ligne-8",
    "Charenton-Ecoles ligne-8",
    "Ecole Vétérinaire de Maisons-Alfort ligne-8",
    "Invalides ligne-8",
    "Invalides ligne-13",
    "Balard ligne-8",
    "Balard tramway-3a",
    "Créteil-L'Echat (Hôpital Henri Mondor) ligne-8",
    "Créteil-Université ligne-8",
    "Maisons-Alfort-Les Juilliottes ligne-8",
    "Boucicaut ligne-8",
    "Lourmel ligne-8",
    "Madeleine ligne-8",
    "Madeleine ligne-14",
    "Madeleine ligne-12",
    "Créteil-Préfecture (Hôtel de Ville) ligne-8",
    "Billancourt ligne-9",
    "Saint-Philippe du Roule ligne-9",
    "Ranelagh ligne-9",
    "Buzenval ligne-9",
    "Alma-Marceau ligne-9",
    "Robespierre ligne-9",
    "Pont de Sèvres ligne-9",
    "La Muette ligne-9",
    "Exelmans ligne-9",
    "Voltaire (Léon Blum) ligne-9",
    "Charonne ligne-9",
    "Jasmin ligne-9",
    "Mairie de Montreuil ligne-9",
    "Iéna ligne-9",
    "Michel-Ange-Molitor ligne-10",
    "Michel-Ange-Molitor ligne-9",
    "Porte de Saint-Cloud ligne-9",
    "Croix-de-Chavaux (Jacques Duclos) ligne-9",
    "Michel-Ange-Auteuil ligne-10",
    "Michel-Ange-Auteuil ligne-9",
    "Porte de Montreuil tramway-3b",
    "Porte de Montreuil ligne-9",
    "Miromesnil ligne-13",
    "Miromesnil ligne-9",
    "Saint-Ambroise ligne-9",
    "Saint-Augustin ligne-9",
    "Maraichers ligne-9",
    "Marcel Sembat ligne-9",
    "Rue des Boulets ligne-9",
    "Rue de la Pompe (Avenue Georges Mandel) ligne-9",
    "Ségur ligne-10",
    "Maubert-Mutualité ligne-10",
    "Sèvres-Babylone ligne-10",
    "Sèvres-Babylone ligne-12",
    "Vaneau ligne-10",
    "Mabillon ligne-10",
    "Eglise d'Auteuil ligne-10",
    "Javel-André-Citroen ligne-10",
    "Nanterre-Ville rer-a",
    "Nanterre-Université rer-a",
    "Sucy Bonneuil rer-a",
    "Bussy-Saint-Georges rer-a",
    "Saint-Germain-en-Laye rer-a",
    "Nogent-sur-Marne rer-a",
    "Saint-Maur Créteil rer-a",
    "Noisiel rer-a",
    "Châtelet-Les Halles rer-a",
    "Châtelet-Les Halles rer-b",
    "Neuilly-Plaisance rer-a",
    "Torcy rer-a",
    "Auber rer-a",
    "Noisy-le-Grand (Mont d'Est) rer-a",
    "Vincennes rer-a",
    "Poissy rer-a",
    "La Varenne-Chennevières rer-a",
    "Joinville-le-Pont rer-a",
    "Champigny rer-a",
    "Chatou-Croissy rer-a",
    "Cergy-Préfecture rer-a",
    "Cergy-Saint-Christophe rer-a",
    "Noisy-Champs rer-a",
    "Fontenay-sous-Bois rer-a",
    "Maisons-Laffitte rer-a",
    "Achères-Ville rer-a",
    "Nanterre-Préfecture rer-a",
    "Le Parc de Saint-Maur rer-a",
    "Houilles Carrières-sur-Seine rer-a",
    "Val d'europe rer-a",
    "Le Vésinet-Le Pecq rer-a",
    "Cergy-Le-Haut rer-a",
    "Le Vésinet-Centre rer-a",
    "Val de Fontenay rer-a",
    "Acheres Grand Cormier rer-a",
    "Sartrouville rer-a",
    "Rueil-Malmaison rer-a",
    "Marne-la-Vallée Chessy rer-a"
]